export const PHONE_BRAND_OPTIONS = [
  "Apple",
  "Samsung",
  "Xiaomi",
  "Redmi",
  "POCO",
  "Huawei",
  "Honor",
  "Oppo",
  "Vivo",
  "Realme",
  "OnePlus",
  "Google",
  "Nokia",
  "Motorola",
  "Sony",
  "Infinix",
  "Tecno",
] as const;

export const PHONE_STORAGE_OPTIONS = [
  "16GB",
  "32GB",
  "64GB",
  "128GB",
  "256GB",
  "512GB",
  "1TB",
  "2TB",
  "4TB",
] as const;

export const PHONE_COLOR_OPTIONS = [
  "Black",
  "White",
  "Silver",
  "Gray",
  "Gold",
  "Rose Gold",
  "Blue",
  "Navy",
  "Green",
  "Mint",
  "Purple",
  "Lavender",
  "Pink",
  "Red",
  "Orange",
  "Yellow",
  "Brown",
  "Beige",
] as const;

export const PHONE_MODELS_BY_BRAND: Record<string, readonly string[]> = {
  Apple: [
    "iPhone X",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone XR",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone 12 mini",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13 mini",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "iPhone SE (2020)",
    "iPhone SE (2022)",
  ],
  Samsung: [
    "Galaxy S20 FE",
    "Galaxy S20",
    "Galaxy S20+",
    "Galaxy S20 Ultra",
    "Galaxy S21",
    "Galaxy S21+",
    "Galaxy S21 Ultra",
    "Galaxy S22",
    "Galaxy S22+",
    "Galaxy S22 Ultra",
    "Galaxy S23",
    "Galaxy S23+",
    "Galaxy S23 Ultra",
    "Galaxy S24",
    "Galaxy S24+",
    "Galaxy S24 Ultra",
    "Galaxy A24",
    "Galaxy A25",
    "Galaxy A34",
    "Galaxy A35",
    "Galaxy A54",
    "Galaxy A55",
    "Galaxy Z Flip 4",
    "Galaxy Z Flip 5",
    "Galaxy Z Flip 6",
    "Galaxy Z Fold 4",
    "Galaxy Z Fold 5",
    "Galaxy Z Fold 6",
  ],
  Xiaomi: [
    "Xiaomi Mi 11",
    "Xiaomi Mi 11 Lite",
    "Xiaomi 11T",
    "Xiaomi 12",
    "Xiaomi 12 Pro",
    "Xiaomi 12T",
    "Xiaomi 12T Pro",
    "Xiaomi 13",
    "Xiaomi 13 Pro",
    "Xiaomi 13 Ultra",
    "Xiaomi 13T",
    "Xiaomi 13T Pro",
    "Xiaomi 14",
    "Xiaomi 14 Pro",
    "Xiaomi 14 Ultra",
    "Xiaomi 14T",
    "Xiaomi 14T Pro",
  ],
  Redmi: [
    "Redmi Note 9",
    "Redmi Note 10",
    "Redmi Note 10 Pro",
    "Redmi Note 11",
    "Redmi Note 11 Pro",
    "Redmi Note 12",
    "Redmi Note 12 Pro",
    "Redmi Note 13",
    "Redmi Note 13 Pro",
    "Redmi Note 13 Pro+",
    "Redmi 10",
    "Redmi 11",
    "Redmi 12",
    "Redmi 13",
  ],
  POCO: [
    "POCO X3 NFC",
    "POCO X3 Pro",
    "POCO X5",
    "POCO X5 Pro",
    "POCO X6",
    "POCO X6 Pro",
    "POCO F3",
    "POCO F4",
    "POCO F4 GT",
    "POCO F5",
    "POCO F5 Pro",
    "POCO F6",
    "POCO F6 Pro",
    "POCO M5",
    "POCO M6 Pro",
  ],
  Huawei: [
    "P30",
    "P30 Pro",
    "P40",
    "P40 Pro",
    "P50",
    "P50 Pro",
    "Mate 30 Pro",
    "Mate 40 Pro",
    "Mate 50 Pro",
    "Mate 60 Pro",
    "Nova 10",
    "Nova 11",
    "Nova 12",
  ],
  Honor: [
    "Honor 50",
    "Honor 60",
    "Honor 70",
    "Honor 80",
    "Honor 90",
    "Honor 100",
    "Honor 200",
    "Honor Magic 4 Pro",
    "Honor Magic 5 Pro",
    "Honor Magic 6 Pro",
    "Honor X8",
    "Honor X9",
    "Honor X9a",
  ],
  Oppo: [
    "Reno 7",
    "Reno 8",
    "Reno 8 Pro",
    "Reno 10",
    "Reno 10 Pro",
    "Reno 11",
    "Reno 11 Pro",
    "Find X5 Pro",
    "Find X5",
    "Find X6 Pro",
    "Find X6",
    "Find X7",
    "Find X7 Ultra",
    "A58",
    "A78",
  ],
  Vivo: [
    "Vivo V23",
    "Vivo V25",
    "Vivo V27",
    "Vivo V27 Pro",
    "Vivo V29",
    "Vivo V29 Pro",
    "Vivo V30",
    "Vivo V30 Pro",
    "Vivo X80",
    "Vivo X90",
    "Vivo X100",
    "Vivo Y27",
    "Vivo Y36",
  ],
  Realme: [
    "Realme 9",
    "Realme 10",
    "Realme 10 Pro",
    "Realme 11",
    "Realme 11 Pro",
    "Realme 11 Pro+",
    "Realme 12",
    "Realme 12 Pro",
    "Realme 12 Pro+",
    "Realme GT 2",
    "Realme GT Neo 3",
    "Realme C53",
    "Realme C55",
  ],
  OnePlus: [
    "OnePlus 8T",
    "OnePlus 9",
    "OnePlus 9 Pro",
    "OnePlus 10T",
    "OnePlus 10 Pro",
    "OnePlus 11",
    "OnePlus 11R",
    "OnePlus 12",
    "OnePlus 12R",
    "OnePlus Nord 2",
    "OnePlus Nord 3",
  ],
  Google: [
    "Pixel 6a",
    "Pixel 6",
    "Pixel 6 Pro",
    "Pixel 7a",
    "Pixel 7",
    "Pixel 7 Pro",
    "Pixel 8",
    "Pixel 8a",
    "Pixel 8 Pro",
    "Pixel 9",
    "Pixel 9 Pro XL",
    "Pixel 9 Pro",
  ],
  Nokia: [
    "Nokia G11",
    "Nokia G21",
    "Nokia G22",
    "Nokia G42",
    "Nokia X20",
    "Nokia X30",
    "Nokia C22",
    "Nokia C32",
  ],
  Motorola: [
    "Moto G32",
    "Moto G54",
    "Moto G84",
    "Moto Edge 30",
    "Moto Edge 40",
    "Moto Edge 40 Neo",
    "Moto Edge 50",
    "Moto Edge 50 Pro",
  ],
  Sony: [
    "Xperia 1 III",
    "Xperia 1 IV",
    "Xperia 1 V",
    "Xperia 5 III",
    "Xperia 5 IV",
    "Xperia 5 V",
    "Xperia 10 IV",
    "Xperia 10 V",
  ],
  Infinix: [
    "Infinix Note 12",
    "Infinix Note 30",
    "Infinix Note 40",
    "Infinix Zero 20",
    "Infinix Zero 30",
    "Infinix Hot 20",
    "Infinix Hot 30",
  ],
  Tecno: [
    "Tecno Camon 19",
    "Tecno Camon 20",
    "Tecno Camon 30",
    "Tecno Spark 10",
    "Tecno Spark 20",
    "Tecno Phantom X2",
    "Tecno Phantom V Fold",
  ],
};

export function getPhoneModelsByBrand(brand?: string): readonly string[] {
  if (!brand) return [];
  return PHONE_MODELS_BY_BRAND[brand] ?? [];
}
